[CRITICAL] [10:02:54:HPOlib.cv] args: ({'filter_size': 8.0, 'fc_depth': 485.0, 'conv1_depth': 392.0},) kwargs: {}
[INFO] [10:02:54:HPOlib.cv] Starting Cross validation
[INFO] [10:02:54:HPOlib.cv] {'filter_size': 8.0, 'fc_depth': 485.0, 'conv1_depth': 392.0}
[INFO] [10:02:54:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 8.0 -fc_depth 485.0 -conv1_depth 392.0
[INFO] [10:02:54:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:21:HPOlib.cv] Result for ParamILS: SAT, 26.501300, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-2-54-713711_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:21:HPOlib.cv] [INFO] [10:02:54:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:21:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
2.05/26.46	  File "../convolutional-hpolib.py", line 231, in train_mnist
2.05/26.46	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
2.05/26.46	ValueError: invalid literal for int() with base 10: '8.0'

[INFO] [10:03:21:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 26.501300, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-2-54-713711_run_instance.out.The output status is not "SAT"

[INFO] [10:03:21:HPOlib.cv] Finished CV
[INFO] [10:03:21:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:21:HPOlib.cv] args: ({'filter_size': 13.0, 'fc_depth': 358.0, 'conv1_depth': 512.0},) kwargs: {}
[INFO] [10:03:21:HPOlib.cv] Starting Cross validation
[INFO] [10:03:21:HPOlib.cv] {'filter_size': 13.0, 'fc_depth': 358.0, 'conv1_depth': 512.0}
[INFO] [10:03:21:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 13.0 -fc_depth 358.0 -conv1_depth 512.0
[INFO] [10:03:21:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:22:HPOlib.cv] Result for ParamILS: SAT, 1.017410, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-21-540079_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:22:HPOlib.cv] [INFO] [10:03:21:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:22:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.73/0.98	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.73/0.98	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.73/0.98	ValueError: invalid literal for int() with base 10: '13.0'

[INFO] [10:03:22:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.017410, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-21-540079_run_instance.out.The output status is not "SAT"

[INFO] [10:03:22:HPOlib.cv] Finished CV
[INFO] [10:03:22:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:22:HPOlib.cv] args: ({'filter_size': 12.0, 'fc_depth': 299.0, 'conv1_depth': 144.0},) kwargs: {}
[INFO] [10:03:22:HPOlib.cv] Starting Cross validation
[INFO] [10:03:22:HPOlib.cv] {'filter_size': 12.0, 'fc_depth': 299.0, 'conv1_depth': 144.0}
[INFO] [10:03:22:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 12.0 -fc_depth 299.0 -conv1_depth 144.0
[INFO] [10:03:22:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:24:HPOlib.cv] Result for ParamILS: SAT, 1.118590, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-22-860445_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:24:HPOlib.cv] [INFO] [10:03:22:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:24:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.83/1.08	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.83/1.08	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.83/1.08	ValueError: invalid literal for int() with base 10: '12.0'

[INFO] [10:03:24:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.118590, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-22-860445_run_instance.out.The output status is not "SAT"

[INFO] [10:03:24:HPOlib.cv] Finished CV
[INFO] [10:03:24:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:24:HPOlib.cv] args: ({'filter_size': 5.0, 'fc_depth': 266.0, 'conv1_depth': 394.0},) kwargs: {}
[INFO] [10:03:24:HPOlib.cv] Starting Cross validation
[INFO] [10:03:24:HPOlib.cv] {'filter_size': 5.0, 'fc_depth': 266.0, 'conv1_depth': 394.0}
[INFO] [10:03:24:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 5.0 -fc_depth 266.0 -conv1_depth 394.0
[INFO] [10:03:24:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:25:HPOlib.cv] Result for ParamILS: SAT, 1.025310, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-24-247988_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:25:HPOlib.cv] [INFO] [10:03:24:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:25:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.74/0.99	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.74/0.99	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.74/0.99	ValueError: invalid literal for int() with base 10: '5.0'

[INFO] [10:03:25:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.025310, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-24-247988_run_instance.out.The output status is not "SAT"

[INFO] [10:03:25:HPOlib.cv] Finished CV
[INFO] [10:03:25:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:25:HPOlib.cv] args: ({'filter_size': 7.0, 'fc_depth': 417.0, 'conv1_depth': 376.0},) kwargs: {}
[INFO] [10:03:25:HPOlib.cv] Starting Cross validation
[INFO] [10:03:25:HPOlib.cv] {'filter_size': 7.0, 'fc_depth': 417.0, 'conv1_depth': 376.0}
[INFO] [10:03:25:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 7.0 -fc_depth 417.0 -conv1_depth 376.0
[INFO] [10:03:25:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:26:HPOlib.cv] Result for ParamILS: SAT, 1.050630, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-25-570479_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:26:HPOlib.cv] [INFO] [10:03:25:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:26:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.83/1.01	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.83/1.01	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.83/1.01	ValueError: invalid literal for int() with base 10: '7.0'

[INFO] [10:03:26:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.050630, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-25-570479_run_instance.out.The output status is not "SAT"

[INFO] [10:03:26:HPOlib.cv] Finished CV
[INFO] [10:03:26:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:26:HPOlib.cv] args: ({'filter_size': 10.0, 'fc_depth': 288.0, 'conv1_depth': 64.0},) kwargs: {}
[INFO] [10:03:26:HPOlib.cv] Starting Cross validation
[INFO] [10:03:26:HPOlib.cv] {'filter_size': 10.0, 'fc_depth': 288.0, 'conv1_depth': 64.0}
[INFO] [10:03:26:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 10.0 -fc_depth 288.0 -conv1_depth 64.0
[INFO] [10:03:26:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:27:HPOlib.cv] Result for ParamILS: SAT, 0.958691, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-26-845522_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:27:HPOlib.cv] [INFO] [10:03:26:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:27:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.71/0.92	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.71/0.92	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.71/0.92	ValueError: invalid literal for int() with base 10: '10.0'

[INFO] [10:03:27:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 0.958691, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-26-845522_run_instance.out.The output status is not "SAT"

[INFO] [10:03:27:HPOlib.cv] Finished CV
[INFO] [10:03:27:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:27:HPOlib.cv] args: ({'filter_size': 12.0, 'fc_depth': 147.0, 'conv1_depth': 38.0},) kwargs: {}
[INFO] [10:03:27:HPOlib.cv] Starting Cross validation
[INFO] [10:03:27:HPOlib.cv] {'filter_size': 12.0, 'fc_depth': 147.0, 'conv1_depth': 38.0}
[INFO] [10:03:27:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 12.0 -fc_depth 147.0 -conv1_depth 38.0
[INFO] [10:03:27:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:29:HPOlib.cv] Result for ParamILS: SAT, 1.054210, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-28-56261_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:29:HPOlib.cv] [INFO] [10:03:28:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:29:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.84/1.02	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.84/1.02	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.84/1.02	ValueError: invalid literal for int() with base 10: '12.0'

[INFO] [10:03:29:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.054210, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-28-56261_run_instance.out.The output status is not "SAT"

[INFO] [10:03:29:HPOlib.cv] Finished CV
[INFO] [10:03:29:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:29:HPOlib.cv] args: ({'filter_size': 9.0, 'fc_depth': 196.0, 'conv1_depth': 340.0},) kwargs: {}
[INFO] [10:03:29:HPOlib.cv] Starting Cross validation
[INFO] [10:03:29:HPOlib.cv] {'filter_size': 9.0, 'fc_depth': 196.0, 'conv1_depth': 340.0}
[INFO] [10:03:29:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 9.0 -fc_depth 196.0 -conv1_depth 340.0
[INFO] [10:03:29:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:30:HPOlib.cv] Result for ParamILS: SAT, 1.109020, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-29-370569_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:30:HPOlib.cv] [INFO] [10:03:29:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:30:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.82/1.07	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.82/1.07	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.82/1.07	ValueError: invalid literal for int() with base 10: '9.0'

[INFO] [10:03:30:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.109020, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-29-370569_run_instance.out.The output status is not "SAT"

[INFO] [10:03:30:HPOlib.cv] Finished CV
[INFO] [10:03:30:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:30:HPOlib.cv] args: ({'filter_size': 5.0, 'fc_depth': 491.0, 'conv1_depth': 394.0},) kwargs: {}
[INFO] [10:03:30:HPOlib.cv] Starting Cross validation
[INFO] [10:03:30:HPOlib.cv] {'filter_size': 5.0, 'fc_depth': 491.0, 'conv1_depth': 394.0}
[INFO] [10:03:30:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 5.0 -fc_depth 491.0 -conv1_depth 394.0
[INFO] [10:03:30:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:31:HPOlib.cv] Result for ParamILS: SAT, 1.008790, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-30-809403_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:31:HPOlib.cv] [INFO] [10:03:30:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:31:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.72/0.97	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.72/0.97	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.72/0.97	ValueError: invalid literal for int() with base 10: '5.0'

[INFO] [10:03:31:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.008790, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-30-809403_run_instance.out.The output status is not "SAT"

[INFO] [10:03:31:HPOlib.cv] Finished CV
[INFO] [10:03:31:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:32:HPOlib.cv] args: ({'filter_size': 12.0, 'fc_depth': 191.0, 'conv1_depth': 284.0},) kwargs: {}
[INFO] [10:03:32:HPOlib.cv] Starting Cross validation
[INFO] [10:03:32:HPOlib.cv] {'filter_size': 12.0, 'fc_depth': 191.0, 'conv1_depth': 284.0}
[INFO] [10:03:32:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 12.0 -fc_depth 191.0 -conv1_depth 284.0
[INFO] [10:03:32:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:33:HPOlib.cv] Result for ParamILS: SAT, 1.005150, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-32-110885_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:33:HPOlib.cv] [INFO] [10:03:32:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:33:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.74/0.97	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.74/0.97	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.74/0.97	ValueError: invalid literal for int() with base 10: '12.0'

[INFO] [10:03:33:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.005150, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-32-110885_run_instance.out.The output status is not "SAT"

[INFO] [10:03:33:HPOlib.cv] Finished CV
[INFO] [10:03:33:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:33:HPOlib.cv] args: ({'filter_size': 4.0, 'fc_depth': 231.0, 'conv1_depth': 210.0},) kwargs: {}
[INFO] [10:03:33:HPOlib.cv] Starting Cross validation
[INFO] [10:03:33:HPOlib.cv] {'filter_size': 4.0, 'fc_depth': 231.0, 'conv1_depth': 210.0}
[INFO] [10:03:33:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 4.0 -fc_depth 231.0 -conv1_depth 210.0
[INFO] [10:03:33:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:34:HPOlib.cv] Result for ParamILS: SAT, 1.040780, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-33-462915_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:34:HPOlib.cv] [INFO] [10:03:33:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:34:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.83/1.00	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.83/1.00	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.83/1.00	ValueError: invalid literal for int() with base 10: '4.0'

[INFO] [10:03:34:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.040780, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-33-462915_run_instance.out.The output status is not "SAT"

[INFO] [10:03:34:HPOlib.cv] Finished CV
[INFO] [10:03:34:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:34:HPOlib.cv] args: ({'filter_size': 2.0, 'fc_depth': 400.0, 'conv1_depth': 48.0},) kwargs: {}
[INFO] [10:03:34:HPOlib.cv] Starting Cross validation
[INFO] [10:03:34:HPOlib.cv] {'filter_size': 2.0, 'fc_depth': 400.0, 'conv1_depth': 48.0}
[INFO] [10:03:34:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 2.0 -fc_depth 400.0 -conv1_depth 48.0
[INFO] [10:03:34:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:35:HPOlib.cv] Result for ParamILS: SAT, 0.951781, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-34-759280_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:35:HPOlib.cv] [INFO] [10:03:34:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:35:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.71/0.91	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.71/0.91	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.71/0.91	ValueError: invalid literal for int() with base 10: '2.0'

[INFO] [10:03:35:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 0.951781, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-34-759280_run_instance.out.The output status is not "SAT"

[INFO] [10:03:35:HPOlib.cv] Finished CV
[INFO] [10:03:35:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:35:HPOlib.cv] args: ({'filter_size': 7.0, 'fc_depth': 159.0, 'conv1_depth': 120.0},) kwargs: {}
[INFO] [10:03:35:HPOlib.cv] Starting Cross validation
[INFO] [10:03:35:HPOlib.cv] {'filter_size': 7.0, 'fc_depth': 159.0, 'conv1_depth': 120.0}
[INFO] [10:03:35:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 7.0 -fc_depth 159.0 -conv1_depth 120.0
[INFO] [10:03:35:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:37:HPOlib.cv] Result for ParamILS: SAT, 0.950097, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-35-939761_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:37:HPOlib.cv] [INFO] [10:03:35:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:36:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.71/0.91	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.71/0.91	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.71/0.91	ValueError: invalid literal for int() with base 10: '7.0'

[INFO] [10:03:37:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 0.950097, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-35-939761_run_instance.out.The output status is not "SAT"

[INFO] [10:03:37:HPOlib.cv] Finished CV
[INFO] [10:03:37:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:37:HPOlib.cv] args: ({'filter_size': 10.0, 'fc_depth': 308.0, 'conv1_depth': 488.0},) kwargs: {}
[INFO] [10:03:37:HPOlib.cv] Starting Cross validation
[INFO] [10:03:37:HPOlib.cv] {'filter_size': 10.0, 'fc_depth': 308.0, 'conv1_depth': 488.0}
[INFO] [10:03:37:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 10.0 -fc_depth 308.0 -conv1_depth 488.0
[INFO] [10:03:37:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:38:HPOlib.cv] Result for ParamILS: SAT, 0.949779, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-37-134340_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:38:HPOlib.cv] [INFO] [10:03:37:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:38:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.74/0.91	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.74/0.91	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.74/0.91	ValueError: invalid literal for int() with base 10: '10.0'

[INFO] [10:03:38:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 0.949779, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-37-134340_run_instance.out.The output status is not "SAT"

[INFO] [10:03:38:HPOlib.cv] Finished CV
[INFO] [10:03:38:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:38:HPOlib.cv] args: ({'filter_size': 13.0, 'fc_depth': 238.0, 'conv1_depth': 100.0},) kwargs: {}
[INFO] [10:03:38:HPOlib.cv] Starting Cross validation
[INFO] [10:03:38:HPOlib.cv] {'filter_size': 13.0, 'fc_depth': 238.0, 'conv1_depth': 100.0}
[INFO] [10:03:38:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 13.0 -fc_depth 238.0 -conv1_depth 100.0
[INFO] [10:03:38:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:39:HPOlib.cv] Result for ParamILS: SAT, 0.954453, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-38-336914_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:39:HPOlib.cv] [INFO] [10:03:38:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:39:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.73/0.92	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.73/0.92	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.73/0.92	ValueError: invalid literal for int() with base 10: '13.0'

[INFO] [10:03:39:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 0.954453, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-38-336914_run_instance.out.The output status is not "SAT"

[INFO] [10:03:39:HPOlib.cv] Finished CV
[INFO] [10:03:39:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:39:HPOlib.cv] args: ({'filter_size': 6.0, 'fc_depth': 440.0, 'conv1_depth': 484.0},) kwargs: {}
[INFO] [10:03:39:HPOlib.cv] Starting Cross validation
[INFO] [10:03:39:HPOlib.cv] {'filter_size': 6.0, 'fc_depth': 440.0, 'conv1_depth': 484.0}
[INFO] [10:03:39:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 6.0 -fc_depth 440.0 -conv1_depth 484.0
[INFO] [10:03:39:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:40:HPOlib.cv] Result for ParamILS: SAT, 1.059240, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-39-519811_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:40:HPOlib.cv] [INFO] [10:03:39:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:40:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.84/1.02	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.84/1.02	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.84/1.02	ValueError: invalid literal for int() with base 10: '6.0'

[INFO] [10:03:40:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.059240, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-39-519811_run_instance.out.The output status is not "SAT"

[INFO] [10:03:40:HPOlib.cv] Finished CV
[INFO] [10:03:40:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:40:HPOlib.cv] args: ({'filter_size': 8.0, 'fc_depth': 409.0, 'conv1_depth': 420.0},) kwargs: {}
[INFO] [10:03:40:HPOlib.cv] Starting Cross validation
[INFO] [10:03:40:HPOlib.cv] {'filter_size': 8.0, 'fc_depth': 409.0, 'conv1_depth': 420.0}
[INFO] [10:03:40:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 8.0 -fc_depth 409.0 -conv1_depth 420.0
[INFO] [10:03:40:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:42:HPOlib.cv] Result for ParamILS: SAT, 1.041740, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-40-867823_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:42:HPOlib.cv] [INFO] [10:03:40:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:41:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.84/1.00	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.84/1.00	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.84/1.00	ValueError: invalid literal for int() with base 10: '8.0'

[INFO] [10:03:42:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.041740, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-40-867823_run_instance.out.The output status is not "SAT"

[INFO] [10:03:42:HPOlib.cv] Finished CV
[INFO] [10:03:42:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:42:HPOlib.cv] args: ({'filter_size': 6.0, 'fc_depth': 29.0, 'conv1_depth': 404.0},) kwargs: {}
[INFO] [10:03:42:HPOlib.cv] Starting Cross validation
[INFO] [10:03:42:HPOlib.cv] {'filter_size': 6.0, 'fc_depth': 29.0, 'conv1_depth': 404.0}
[INFO] [10:03:42:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 6.0 -fc_depth 29.0 -conv1_depth 404.0
[INFO] [10:03:42:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:43:HPOlib.cv] Result for ParamILS: SAT, 1.103920, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-42-215546_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:43:HPOlib.cv] [INFO] [10:03:42:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:43:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.84/1.06	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.84/1.06	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.84/1.06	ValueError: invalid literal for int() with base 10: '6.0'

[INFO] [10:03:43:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.103920, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-42-215546_run_instance.out.The output status is not "SAT"

[INFO] [10:03:43:HPOlib.cv] Finished CV
[INFO] [10:03:43:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:43:HPOlib.cv] args: ({'filter_size': 4.0, 'fc_depth': 25.0, 'conv1_depth': 346.0},) kwargs: {}
[INFO] [10:03:43:HPOlib.cv] Starting Cross validation
[INFO] [10:03:43:HPOlib.cv] {'filter_size': 4.0, 'fc_depth': 25.0, 'conv1_depth': 346.0}
[INFO] [10:03:43:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 4.0 -fc_depth 25.0 -conv1_depth 346.0
[INFO] [10:03:43:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:44:HPOlib.cv] Result for ParamILS: SAT, 1.054970, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-43-653368_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:44:HPOlib.cv] [INFO] [10:03:43:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:44:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.83/1.02	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.83/1.02	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.83/1.02	ValueError: invalid literal for int() with base 10: '4.0'

[INFO] [10:03:44:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.054970, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-43-653368_run_instance.out.The output status is not "SAT"

[INFO] [10:03:44:HPOlib.cv] Finished CV
[INFO] [10:03:44:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:44:HPOlib.cv] args: ({'filter_size': 6.0, 'fc_depth': 487.0, 'conv1_depth': 376.0},) kwargs: {}
[INFO] [10:03:44:HPOlib.cv] Starting Cross validation
[INFO] [10:03:44:HPOlib.cv] {'filter_size': 6.0, 'fc_depth': 487.0, 'conv1_depth': 376.0}
[INFO] [10:03:44:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 6.0 -fc_depth 487.0 -conv1_depth 376.0
[INFO] [10:03:44:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:46:HPOlib.cv] Result for ParamILS: SAT, 1.024640, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-44-973765_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:46:HPOlib.cv] [INFO] [10:03:45:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:46:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.73/0.99	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.73/0.99	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.73/0.99	ValueError: invalid literal for int() with base 10: '6.0'

[INFO] [10:03:46:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.024640, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-44-973765_run_instance.out.The output status is not "SAT"

[INFO] [10:03:46:HPOlib.cv] Finished CV
[INFO] [10:03:46:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:46:HPOlib.cv] args: ({'filter_size': 1.0, 'fc_depth': 30.0, 'conv1_depth': 278.0},) kwargs: {}
[INFO] [10:03:46:HPOlib.cv] Starting Cross validation
[INFO] [10:03:46:HPOlib.cv] {'filter_size': 1.0, 'fc_depth': 30.0, 'conv1_depth': 278.0}
[INFO] [10:03:46:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 1.0 -fc_depth 30.0 -conv1_depth 278.0
[INFO] [10:03:46:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:47:HPOlib.cv] Result for ParamILS: SAT, 1.020600, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-46-329129_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:47:HPOlib.cv] [INFO] [10:03:46:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:47:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.73/0.98	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.73/0.98	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.73/0.98	ValueError: invalid literal for int() with base 10: '1.0'

[INFO] [10:03:47:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.020600, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-46-329129_run_instance.out.The output status is not "SAT"

[INFO] [10:03:47:HPOlib.cv] Finished CV
[INFO] [10:03:47:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:47:HPOlib.cv] args: ({'filter_size': 3.0, 'fc_depth': 104.0, 'conv1_depth': 320.0},) kwargs: {}
[INFO] [10:03:47:HPOlib.cv] Starting Cross validation
[INFO] [10:03:47:HPOlib.cv] {'filter_size': 3.0, 'fc_depth': 104.0, 'conv1_depth': 320.0}
[INFO] [10:03:47:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 3.0 -fc_depth 104.0 -conv1_depth 320.0
[INFO] [10:03:47:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:48:HPOlib.cv] Result for ParamILS: SAT, 0.976329, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-47-657600_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:48:HPOlib.cv] [INFO] [10:03:47:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:48:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.70/0.94	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.70/0.94	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.70/0.94	ValueError: invalid literal for int() with base 10: '3.0'

[INFO] [10:03:48:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 0.976329, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-47-657600_run_instance.out.The output status is not "SAT"

[INFO] [10:03:48:HPOlib.cv] Finished CV
[INFO] [10:03:48:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:48:HPOlib.cv] args: ({'filter_size': 9.0, 'fc_depth': 510.0, 'conv1_depth': 454.0},) kwargs: {}
[INFO] [10:03:48:HPOlib.cv] Starting Cross validation
[INFO] [10:03:48:HPOlib.cv] {'filter_size': 9.0, 'fc_depth': 510.0, 'conv1_depth': 454.0}
[INFO] [10:03:48:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 9.0 -fc_depth 510.0 -conv1_depth 454.0
[INFO] [10:03:48:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:49:HPOlib.cv] Result for ParamILS: SAT, 0.954952, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-48-885583_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:49:HPOlib.cv] [INFO] [10:03:48:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:49:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.72/0.92	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.72/0.92	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.72/0.92	ValueError: invalid literal for int() with base 10: '9.0'

[INFO] [10:03:49:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 0.954952, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-48-885583_run_instance.out.The output status is not "SAT"

[INFO] [10:03:49:HPOlib.cv] Finished CV
[INFO] [10:03:49:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:49:HPOlib.cv] args: ({'filter_size': 1.0, 'fc_depth': 81.0, 'conv1_depth': 246.0},) kwargs: {}
[INFO] [10:03:50:HPOlib.cv] Starting Cross validation
[INFO] [10:03:50:HPOlib.cv] {'filter_size': 1.0, 'fc_depth': 81.0, 'conv1_depth': 246.0}
[INFO] [10:03:50:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 1.0 -fc_depth 81.0 -conv1_depth 246.0
[INFO] [10:03:50:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:51:HPOlib.cv] Result for ParamILS: SAT, 1.051160, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-50-94909_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:51:HPOlib.cv] [INFO] [10:03:50:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:51:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.83/1.01	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.83/1.01	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.83/1.01	ValueError: invalid literal for int() with base 10: '1.0'

[INFO] [10:03:51:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.051160, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-50-94909_run_instance.out.The output status is not "SAT"

[INFO] [10:03:51:HPOlib.cv] Finished CV
[INFO] [10:03:51:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:51:HPOlib.cv] args: ({'filter_size': 3.0, 'fc_depth': 120.0, 'conv1_depth': 316.0},) kwargs: {}
[INFO] [10:03:51:HPOlib.cv] Starting Cross validation
[INFO] [10:03:51:HPOlib.cv] {'filter_size': 3.0, 'fc_depth': 120.0, 'conv1_depth': 316.0}
[INFO] [10:03:51:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 3.0 -fc_depth 120.0 -conv1_depth 316.0
[INFO] [10:03:51:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:52:HPOlib.cv] Result for ParamILS: SAT, 1.108970, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-51-480789_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:52:HPOlib.cv] [INFO] [10:03:51:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:52:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.84/1.07	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.84/1.07	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.84/1.07	ValueError: invalid literal for int() with base 10: '3.0'

[INFO] [10:03:52:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.108970, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-51-480789_run_instance.out.The output status is not "SAT"

[INFO] [10:03:52:HPOlib.cv] Finished CV
[INFO] [10:03:52:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:52:HPOlib.cv] args: ({'filter_size': 9.0, 'fc_depth': 455.0, 'conv1_depth': 450.0},) kwargs: {}
[INFO] [10:03:52:HPOlib.cv] Starting Cross validation
[INFO] [10:03:52:HPOlib.cv] {'filter_size': 9.0, 'fc_depth': 455.0, 'conv1_depth': 450.0}
[INFO] [10:03:52:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 9.0 -fc_depth 455.0 -conv1_depth 450.0
[INFO] [10:03:52:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:53:HPOlib.cv] Result for ParamILS: SAT, 0.964964, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-52-930026_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:53:HPOlib.cv] [INFO] [10:03:52:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:53:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.73/0.93	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.73/0.93	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.73/0.93	ValueError: invalid literal for int() with base 10: '9.0'

[INFO] [10:03:53:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 0.964964, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-52-930026_run_instance.out.The output status is not "SAT"

[INFO] [10:03:53:HPOlib.cv] Finished CV
[INFO] [10:03:53:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:54:HPOlib.cv] args: ({'filter_size': 11.0, 'fc_depth': 93.0, 'conv1_depth': 214.0},) kwargs: {}
[INFO] [10:03:54:HPOlib.cv] Starting Cross validation
[INFO] [10:03:54:HPOlib.cv] {'filter_size': 11.0, 'fc_depth': 93.0, 'conv1_depth': 214.0}
[INFO] [10:03:54:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 11.0 -fc_depth 93.0 -conv1_depth 214.0
[INFO] [10:03:54:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:55:HPOlib.cv] Result for ParamILS: SAT, 0.950981, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-54-153680_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:55:HPOlib.cv] [INFO] [10:03:54:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:55:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.73/0.91	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.73/0.91	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.73/0.91	ValueError: invalid literal for int() with base 10: '11.0'

[INFO] [10:03:55:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 0.950981, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-54-153680_run_instance.out.The output status is not "SAT"

[INFO] [10:03:55:HPOlib.cv] Finished CV
[INFO] [10:03:55:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:55:HPOlib.cv] args: ({'filter_size': 8.0, 'fc_depth': 350.0, 'conv1_depth': 170.0},) kwargs: {}
[INFO] [10:03:55:HPOlib.cv] Starting Cross validation
[INFO] [10:03:55:HPOlib.cv] {'filter_size': 8.0, 'fc_depth': 350.0, 'conv1_depth': 170.0}
[INFO] [10:03:55:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 8.0 -fc_depth 350.0 -conv1_depth 170.0
[INFO] [10:03:55:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:56:HPOlib.cv] Result for ParamILS: SAT, 1.011250, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-55-385214_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:56:HPOlib.cv] [INFO] [10:03:55:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:56:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.73/0.97	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.73/0.97	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.73/0.97	ValueError: invalid literal for int() with base 10: '8.0'

[INFO] [10:03:56:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.011250, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-55-385214_run_instance.out.The output status is not "SAT"

[INFO] [10:03:56:HPOlib.cv] Finished CV
[INFO] [10:03:56:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:56:HPOlib.cv] args: ({'filter_size': 9.0, 'fc_depth': 461.0, 'conv1_depth': 508.0},) kwargs: {}
[INFO] [10:03:56:HPOlib.cv] Starting Cross validation
[INFO] [10:03:56:HPOlib.cv] {'filter_size': 9.0, 'fc_depth': 461.0, 'conv1_depth': 508.0}
[INFO] [10:03:56:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 9.0 -fc_depth 461.0 -conv1_depth 508.0
[INFO] [10:03:56:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:57:HPOlib.cv] Result for ParamILS: SAT, 0.979044, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-56-717357_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:57:HPOlib.cv] [INFO] [10:03:56:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:57:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.73/0.94	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.73/0.94	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.73/0.94	ValueError: invalid literal for int() with base 10: '9.0'

[INFO] [10:03:57:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 0.979044, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-56-717357_run_instance.out.The output status is not "SAT"

[INFO] [10:03:57:HPOlib.cv] Finished CV
[INFO] [10:03:57:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:57:HPOlib.cv] args: ({'filter_size': 11.0, 'fc_depth': 84.0, 'conv1_depth': 224.0},) kwargs: {}
[INFO] [10:03:57:HPOlib.cv] Starting Cross validation
[INFO] [10:03:57:HPOlib.cv] {'filter_size': 11.0, 'fc_depth': 84.0, 'conv1_depth': 224.0}
[INFO] [10:03:57:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 11.0 -fc_depth 84.0 -conv1_depth 224.0
[INFO] [10:03:57:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:03:59:HPOlib.cv] Result for ParamILS: SAT, 0.957636, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-57-971871_run_instance.out.The output status is not "SAT"

[ERROR] [10:03:59:HPOlib.cv] [INFO] [10:03:58:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:03:59:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.70/0.92	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.70/0.92	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.70/0.92	ValueError: invalid literal for int() with base 10: '11.0'

[INFO] [10:03:59:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 0.957636, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-57-971871_run_instance.out.The output status is not "SAT"

[INFO] [10:03:59:HPOlib.cv] Finished CV
[INFO] [10:03:59:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:03:59:HPOlib.cv] args: ({'filter_size': 7.0, 'fc_depth': 360.0, 'conv1_depth': 182.0},) kwargs: {}
[INFO] [10:03:59:HPOlib.cv] Starting Cross validation
[INFO] [10:03:59:HPOlib.cv] {'filter_size': 7.0, 'fc_depth': 360.0, 'conv1_depth': 182.0}
[INFO] [10:03:59:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 7.0 -fc_depth 360.0 -conv1_depth 182.0
[INFO] [10:03:59:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:04:00:HPOlib.cv] Result for ParamILS: SAT, 1.020420, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-59-195860_run_instance.out.The output status is not "SAT"

[ERROR] [10:04:00:HPOlib.cv] [INFO] [10:03:59:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:04:00:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.70/0.98	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.70/0.98	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.70/0.98	ValueError: invalid literal for int() with base 10: '7.0'

[INFO] [10:04:00:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.020420, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-3-59-195860_run_instance.out.The output status is not "SAT"

[INFO] [10:04:00:HPOlib.cv] Finished CV
[INFO] [10:04:00:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:04:00:HPOlib.cv] args: ({'filter_size': 14.0, 'fc_depth': 364.0, 'conv1_depth': 506.0},) kwargs: {}
[INFO] [10:04:00:HPOlib.cv] Starting Cross validation
[INFO] [10:04:00:HPOlib.cv] {'filter_size': 14.0, 'fc_depth': 364.0, 'conv1_depth': 506.0}
[INFO] [10:04:00:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 14.0 -fc_depth 364.0 -conv1_depth 506.0
[INFO] [10:04:00:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:04:01:HPOlib.cv] Result for ParamILS: SAT, 0.954034, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-0-534248_run_instance.out.The output status is not "SAT"

[ERROR] [10:04:01:HPOlib.cv] [INFO] [10:04:00:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:04:01:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.74/0.92	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.74/0.92	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.74/0.92	ValueError: invalid literal for int() with base 10: '14.0'

[INFO] [10:04:01:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 0.954034, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-0-534248_run_instance.out.The output status is not "SAT"

[INFO] [10:04:01:HPOlib.cv] Finished CV
[INFO] [10:04:01:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:04:01:HPOlib.cv] args: ({'filter_size': 11.0, 'fc_depth': 323.0, 'conv1_depth': 234.0},) kwargs: {}
[INFO] [10:04:01:HPOlib.cv] Starting Cross validation
[INFO] [10:04:01:HPOlib.cv] {'filter_size': 11.0, 'fc_depth': 323.0, 'conv1_depth': 234.0}
[INFO] [10:04:01:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 11.0 -fc_depth 323.0 -conv1_depth 234.0
[INFO] [10:04:01:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:04:02:HPOlib.cv] Result for ParamILS: SAT, 1.091240, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-1-778180_run_instance.out.The output status is not "SAT"

[ERROR] [10:04:02:HPOlib.cv] [INFO] [10:04:01:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:04:02:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.84/1.05	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.84/1.05	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.84/1.05	ValueError: invalid literal for int() with base 10: '11.0'

[INFO] [10:04:02:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.091240, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-1-778180_run_instance.out.The output status is not "SAT"

[INFO] [10:04:02:HPOlib.cv] Finished CV
[INFO] [10:04:02:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:04:02:HPOlib.cv] args: ({'filter_size': 7.0, 'fc_depth': 366.0, 'conv1_depth': 164.0},) kwargs: {}
[INFO] [10:04:03:HPOlib.cv] Starting Cross validation
[INFO] [10:04:03:HPOlib.cv] {'filter_size': 7.0, 'fc_depth': 366.0, 'conv1_depth': 164.0}
[INFO] [10:04:03:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 7.0 -fc_depth 366.0 -conv1_depth 164.0
[INFO] [10:04:03:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:04:04:HPOlib.cv] Result for ParamILS: SAT, 0.942559, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-3-116721_run_instance.out.The output status is not "SAT"

[ERROR] [10:04:04:HPOlib.cv] [INFO] [10:04:03:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:04:04:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.60/0.90	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.60/0.90	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.60/0.90	ValueError: invalid literal for int() with base 10: '7.0'

[INFO] [10:04:04:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 0.942559, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-3-116721_run_instance.out.The output status is not "SAT"

[INFO] [10:04:04:HPOlib.cv] Finished CV
[INFO] [10:04:04:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:04:04:HPOlib.cv] args: ({'filter_size': 13.0, 'fc_depth': 273.0, 'conv1_depth': 438.0},) kwargs: {}
[INFO] [10:04:04:HPOlib.cv] Starting Cross validation
[INFO] [10:04:04:HPOlib.cv] {'filter_size': 13.0, 'fc_depth': 273.0, 'conv1_depth': 438.0}
[INFO] [10:04:04:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 13.0 -fc_depth 273.0 -conv1_depth 438.0
[INFO] [10:04:04:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:04:05:HPOlib.cv] Result for ParamILS: SAT, 0.952954, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-4-352628_run_instance.out.The output status is not "SAT"

[ERROR] [10:04:05:HPOlib.cv] [INFO] [10:04:04:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:04:05:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.73/0.91	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.73/0.91	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.73/0.91	ValueError: invalid literal for int() with base 10: '13.0'

[INFO] [10:04:05:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 0.952954, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-4-352628_run_instance.out.The output status is not "SAT"

[INFO] [10:04:05:HPOlib.cv] Finished CV
[INFO] [10:04:05:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:04:05:HPOlib.cv] args: ({'filter_size': 6.0, 'fc_depth': 511.0, 'conv1_depth': 4.0},) kwargs: {}
[INFO] [10:04:05:HPOlib.cv] Starting Cross validation
[INFO] [10:04:05:HPOlib.cv] {'filter_size': 6.0, 'fc_depth': 511.0, 'conv1_depth': 4.0}
[INFO] [10:04:05:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 6.0 -fc_depth 511.0 -conv1_depth 4.0
[INFO] [10:04:05:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:04:06:HPOlib.cv] Result for ParamILS: SAT, 1.035400, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-5-587026_run_instance.out.The output status is not "SAT"

[ERROR] [10:04:06:HPOlib.cv] [INFO] [10:04:05:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:04:06:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.80/1.00	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.80/1.00	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.80/1.00	ValueError: invalid literal for int() with base 10: '6.0'

[INFO] [10:04:06:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.035400, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-5-587026_run_instance.out.The output status is not "SAT"

[INFO] [10:04:06:HPOlib.cv] Finished CV
[INFO] [10:04:06:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:04:06:HPOlib.cv] args: ({'filter_size': 5.0, 'fc_depth': 2.0, 'conv1_depth': 278.0},) kwargs: {}
[INFO] [10:04:06:HPOlib.cv] Starting Cross validation
[INFO] [10:04:06:HPOlib.cv] {'filter_size': 5.0, 'fc_depth': 2.0, 'conv1_depth': 278.0}
[INFO] [10:04:06:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 5.0 -fc_depth 2.0 -conv1_depth 278.0
[INFO] [10:04:06:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:04:08:HPOlib.cv] Result for ParamILS: SAT, 1.092340, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-6-988853_run_instance.out.The output status is not "SAT"

[ERROR] [10:04:08:HPOlib.cv] [INFO] [10:04:07:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:04:08:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.84/1.05	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.84/1.05	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.84/1.05	ValueError: invalid literal for int() with base 10: '5.0'

[INFO] [10:04:08:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.092340, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-6-988853_run_instance.out.The output status is not "SAT"

[INFO] [10:04:08:HPOlib.cv] Finished CV
[INFO] [10:04:08:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:04:08:HPOlib.cv] args: ({'filter_size': 2.0, 'fc_depth': 48.0, 'conv1_depth': 274.0},) kwargs: {}
[INFO] [10:04:08:HPOlib.cv] Starting Cross validation
[INFO] [10:04:08:HPOlib.cv] {'filter_size': 2.0, 'fc_depth': 48.0, 'conv1_depth': 274.0}
[INFO] [10:04:08:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 2.0 -fc_depth 48.0 -conv1_depth 274.0
[INFO] [10:04:08:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:04:09:HPOlib.cv] Result for ParamILS: SAT, 1.023240, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-8-351848_run_instance.out.The output status is not "SAT"

[ERROR] [10:04:09:HPOlib.cv] [INFO] [10:04:08:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:04:09:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.69/0.98	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.69/0.98	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.69/0.98	ValueError: invalid literal for int() with base 10: '2.0'

[INFO] [10:04:09:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.023240, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-8-351848_run_instance.out.The output status is not "SAT"

[INFO] [10:04:09:HPOlib.cv] Finished CV
[INFO] [10:04:09:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:04:09:HPOlib.cv] args: ({'filter_size': 4.0, 'fc_depth': 186.0, 'conv1_depth': 324.0},) kwargs: {}
[INFO] [10:04:09:HPOlib.cv] Starting Cross validation
[INFO] [10:04:09:HPOlib.cv] {'filter_size': 4.0, 'fc_depth': 186.0, 'conv1_depth': 324.0}
[INFO] [10:04:09:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 4.0 -fc_depth 186.0 -conv1_depth 324.0
[INFO] [10:04:09:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:04:10:HPOlib.cv] Result for ParamILS: SAT, 0.951385, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-9-695933_run_instance.out.The output status is not "SAT"

[ERROR] [10:04:10:HPOlib.cv] [INFO] [10:04:09:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:04:10:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.71/0.91	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.71/0.91	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.71/0.91	ValueError: invalid literal for int() with base 10: '4.0'

[INFO] [10:04:10:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 0.951385, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-9-695933_run_instance.out.The output status is not "SAT"

[INFO] [10:04:10:HPOlib.cv] Finished CV
[INFO] [10:04:10:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:04:10:HPOlib.cv] args: ({'filter_size': 3.0, 'fc_depth': 220.0, 'conv1_depth': 366.0},) kwargs: {}
[INFO] [10:04:10:HPOlib.cv] Starting Cross validation
[INFO] [10:04:10:HPOlib.cv] {'filter_size': 3.0, 'fc_depth': 220.0, 'conv1_depth': 366.0}
[INFO] [10:04:10:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 3.0 -fc_depth 220.0 -conv1_depth 366.0
[INFO] [10:04:10:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:04:12:HPOlib.cv] Result for ParamILS: SAT, 0.958482, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-10-961615_run_instance.out.The output status is not "SAT"

[ERROR] [10:04:12:HPOlib.cv] [INFO] [10:04:11:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:04:12:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.73/0.92	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.73/0.92	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.73/0.92	ValueError: invalid literal for int() with base 10: '3.0'

[INFO] [10:04:12:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 0.958482, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-10-961615_run_instance.out.The output status is not "SAT"

[INFO] [10:04:12:HPOlib.cv] Finished CV
[INFO] [10:04:12:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:04:12:HPOlib.cv] args: ({'filter_size': 10.0, 'fc_depth': 512.0, 'conv1_depth': 446.0},) kwargs: {}
[INFO] [10:04:12:HPOlib.cv] Starting Cross validation
[INFO] [10:04:12:HPOlib.cv] {'filter_size': 10.0, 'fc_depth': 512.0, 'conv1_depth': 446.0}
[INFO] [10:04:12:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 10.0 -fc_depth 512.0 -conv1_depth 446.0
[INFO] [10:04:12:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:04:13:HPOlib.cv] Result for ParamILS: SAT, 1.015310, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-12-222180_run_instance.out.The output status is not "SAT"

[ERROR] [10:04:13:HPOlib.cv] [INFO] [10:04:12:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:04:13:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.74/0.98	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.74/0.98	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.74/0.98	ValueError: invalid literal for int() with base 10: '10.0'

[INFO] [10:04:13:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.015310, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-12-222180_run_instance.out.The output status is not "SAT"

[INFO] [10:04:13:HPOlib.cv] Finished CV
[INFO] [10:04:13:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:04:13:HPOlib.cv] args: ({'filter_size': 9.0, 'fc_depth': 483.0, 'conv1_depth': 474.0},) kwargs: {}
[INFO] [10:04:13:HPOlib.cv] Starting Cross validation
[INFO] [10:04:13:HPOlib.cv] {'filter_size': 9.0, 'fc_depth': 483.0, 'conv1_depth': 474.0}
[INFO] [10:04:13:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 9.0 -fc_depth 483.0 -conv1_depth 474.0
[INFO] [10:04:13:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:04:14:HPOlib.cv] Result for ParamILS: SAT, 0.953548, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-13-584986_run_instance.out.The output status is not "SAT"

[ERROR] [10:04:14:HPOlib.cv] [INFO] [10:04:13:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:04:14:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.73/0.91	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.73/0.91	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.73/0.91	ValueError: invalid literal for int() with base 10: '9.0'

[INFO] [10:04:14:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 0.953548, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-13-584986_run_instance.out.The output status is not "SAT"

[INFO] [10:04:14:HPOlib.cv] Finished CV
[INFO] [10:04:14:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:04:14:HPOlib.cv] args: ({'filter_size': 8.0, 'fc_depth': 75.0, 'conv1_depth': 244.0},) kwargs: {}
[INFO] [10:04:14:HPOlib.cv] Starting Cross validation
[INFO] [10:04:14:HPOlib.cv] {'filter_size': 8.0, 'fc_depth': 75.0, 'conv1_depth': 244.0}
[INFO] [10:04:14:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 8.0 -fc_depth 75.0 -conv1_depth 244.0
[INFO] [10:04:14:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
[INFO] [10:04:15:HPOlib.cv] Result for ParamILS: SAT, 0.955564, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-14-851522_run_instance.out.The output status is not "SAT"

[ERROR] [10:04:15:HPOlib.cv] [INFO] [10:04:14:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[CRITICAL] [10:04:15:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
1.72/0.92	  File "../convolutional-hpolib.py", line 231, in train_mnist
1.72/0.92	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
1.72/0.92	ValueError: invalid literal for int() with base 10: '8.0'

[INFO] [10:04:15:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 0.955564, 1, 1000000.000000, 0, Please have a look at /root/tf-hpolib/HPOlib/benchmarks/tf-cnn/hyperopt_august2013_mod_23_2016-8-30--10-2-54-227737/2016-8-30--10-4-14-851522_run_instance.out.The output status is not "SAT"

[INFO] [10:04:15:HPOlib.cv] Finished CV
[INFO] [10:04:15:HPOlib.cv] Result: 1000000.000000
[CRITICAL] [10:04:15:HPOlib.cv] args: ({'filter_size': 1.0, 'fc_depth': 159.0, 'conv1_depth': 86.0},) kwargs: {}
[INFO] [10:04:16:HPOlib.cv] Starting Cross validation
[INFO] [10:04:16:HPOlib.cv] {'filter_size': 1.0, 'fc_depth': 159.0, 'conv1_depth': 86.0}
[INFO] [10:04:16:HPOlib.cv] Calling command:
python /usr/local/lib/python2.7/dist-packages/HPOlib-0.1.0-py2.7.egg/HPOlib/runsolver_wrapper.py 0 hyperopt_august2013_mod 0 0 0 -filter_size 1.0 -fc_depth 159.0 -conv1_depth 86.0
[INFO] [10:04:16:HPOlib.cv] --------------RUNNING RUNSOLVER_WRAPPER--------------
